# Generated by Django 3.1.7 on 2021-03-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='date_resolved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
